font_family JetBrainsMono Nerd Font
font_size 12.0
background_opacity 0.88
window_padding_width 10
cursor_shape beam
scrollback_lines 10000
copy_on_select clipboard
enable_audio_bell no
confirm_os_window_close 0
shell /usr/bin/zsh
include colors.conf
