general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

# dim the screen after 2.5 minutes
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# lock after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# suspend after 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
