source = ~/.config/hypr/hyprlock-colors.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    brightness = 0.6
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    rounding = 14
    position = 0, -80
    halign = center
    valign = center
    outer_color = $primary
    inner_color = $surface_variant
    font_color = $on_surface
    check_color = $primary
    fail_color = $error
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
    color = $on_surface
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
    color = $on_surface
}
